Test Lab Python sample
firebase/functions-samples pull request #1069
Opened 2023-04-14 20:26 UTC by kevinthecheung

2023-04-14 20:27 UTC, kevinthecheung commented
@jhuleatt I have not tested this.

2023-04-14 20:30 UTC, jhuleatt commented on Python/testlab-to-slack/main.py
> +        url=os.environ["SLACK_WEBHOOK_URL"],
Can you please use params for this? https://github.com/firebase/firebase-functions-python/pull/2/files

We should eventually have it as a Secret, but secret params aren't supported in Python yet

2023-04-14 20:34 UTC, jhuleatt commented on Python/testlab-to-slack/main.py
> +        url=os.environ["SLACK_WEBHOOK_URL"],
hm, actually the Node sample uses `process.env` at the moment as well. Changing to params will probably change the narrative in the docs, so let's stick to env vars as you have it now

2023-04-14 20:34 UTC, jhuleatt approved these changes
Thank you @kevinthecheung

2023-04-14 20:39 UTC, jhuleatt requested changes
Let's make sure we get a chance to test this before merging

2023-04-19 20:02 UTC, kevinthecheung commented
> Let's make sure we get a chance to test this before merging

Tested, and it works.

2023-04-19 20:04 UTC, merged